# Generated by Django 5.2.1 on 2025-05-28 04:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DraftReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('confidence', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('sender', models.EmailField(max_length=254)),
                ('scenario_type', models.CharField(choices=[('random', 'Random'), ('professional', 'Professional'), ('casual', 'Casual'), ('complaint', 'Complaint'), ('inquiry', 'Inquiry')], default='random', max_length=20)),
                ('is_synthetic', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SystemPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('version', models.IntegerField(unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=False)),
                ('performance_score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_outcome', models.TextField()),
                ('prompt_version', models.IntegerField()),
                ('performance_score', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.email')),
            ],
        ),
        migrations.CreateModel(
            name='OptimizationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('feedback_count', models.IntegerField(default=0)),
                ('performance_improvement', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('new_prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='optimization_runs_new', to='core.systemprompt')),
                ('old_prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimization_runs_old', to='core.systemprompt')),
            ],
        ),
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reasons', models.ManyToManyField(related_name='drafts', to='core.draftreason')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='core.email')),
                ('system_prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.systemprompt')),
            ],
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('accept', 'Accept'), ('reject', 'Reject'), ('edit', 'Edit'), ('ignore', 'Ignore')], max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('edited_content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='core.draft')),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'unique_together': {('key',)},
            },
        ),
        migrations.CreateModel(
            name='ReasonRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.draftreason')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reason_ratings', to='core.userfeedback')),
            ],
            options={
                'unique_together': {('feedback', 'reason')},
            },
        ),
    ]
