# Generated by Django 5.2.1 on 2025-05-30 14:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('optimization_iterations', models.IntegerField(default=0)),
                ('total_emails_processed', models.IntegerField(default=0)),
                ('total_feedback_collected', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='userpreference',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='systemprompt',
            name='version',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='email',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='core.session'),
        ),
        migrations.AddField(
            model_name='systemprompt',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='core.session'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='core.session'),
        ),
    ]
