# Generated by Django 5.2.1 on 2025-05-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_session_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemprompt',
            name='parameters',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
