# Generated by Django 5.2.1 on 2025-05-30 23:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_evaluation_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionConfidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_confidence', models.FloatField(default=0.0)),
                ('system_confidence', models.FloatField(default=0.0)),
                ('confidence_trend', models.FloatField(default=0.0)),
                ('feedback_consistency_score', models.FloatField(default=0.0)),
                ('reasoning_alignment_score', models.FloatField(default=0.0)),
                ('total_feedback_count', models.IntegerField(default=0)),
                ('consistent_feedback_streak', models.IntegerField(default=0)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='confidence_tracker', to='core.session')),
            ],
            options={
                'ordering': ['-last_calculated'],
            },
        ),
    ]
