# Generated by Django 5.2.1 on 2025-05-30 23:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sessionconfidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_feedback_ids', models.JSONField(default=list)),
                ('preference_category', models.CharField(max_length=100)),
                ('preference_text', models.TextField()),
                ('confidence_score', models.FloatField()),
                ('extraction_method', models.CharField(max_length=100)),
                ('supporting_evidence', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('auto_extracted', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_preferences', to='core.session')),
            ],
            options={
                'ordering': ['-confidence_score', '-updated_at'],
                'indexes': [models.Index(fields=['session', 'preference_category'], name='core_extrac_session_be968c_idx'), models.Index(fields=['confidence_score'], name='core_extrac_confide_edeb1a_idx')],
            },
        ),
    ]
