# Generated by Django 5.2.1 on 2025-06-01 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_make_evaluation_datasets_global'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='systemprompt',
            unique_together={('session', 'version')},
        ),
    ]
