# Generated by Django 5.2.1 on 2025-06-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_systemprompt_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='PromptLab',
        ),
        migrations.RemoveIndex(
            model_name='extractedpreference',
            name='core_extrac_session_be968c_idx',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='session',
            new_name='prompt_lab',
        ),
        migrations.RenameField(
            model_name='evaluationdataset',
            old_name='session',
            new_name='prompt_lab',
        ),
        migrations.RenameField(
            model_name='extractedpreference',
            old_name='session',
            new_name='prompt_lab',
        ),
        migrations.RenameField(
            model_name='sessionconfidence',
            old_name='session',
            new_name='prompt_lab',
        ),
        migrations.RenameField(
            model_name='systemprompt',
            old_name='session',
            new_name='prompt_lab',
        ),
        migrations.RenameField(
            model_name='userpreference',
            old_name='session',
            new_name='prompt_lab',
        ),
        migrations.AlterUniqueTogether(
            name='systemprompt',
            unique_together={('prompt_lab', 'version')},
        ),
        migrations.AddIndex(
            model_name='extractedpreference',
            index=models.Index(fields=['prompt_lab', 'preference_category'], name='core_extrac_prompt__175136_idx'),
        ),
    ]
