# Generated by Django 5.2.1 on 2025-06-01 16:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_sessionconfidence_promptlabconfidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField()),
                ('output_variations', models.JSONField(default=list)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('ready', 'Ready for Curation'), ('curating', 'Being Curated'), ('promoted', 'Promoted to Real Case'), ('discarded', 'Discarded')], default='generating', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generation_metadata', models.JSONField(blank=True, default=dict)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_cases', to='core.evaluationdataset')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['dataset', 'status'], name='core_draftc_dataset_a5753b_idx'), models.Index(fields=['status', 'created_at'], name='core_draftc_status_ec2f89_idx')],
            },
        ),
    ]
