# Generated by Django 5.2.1 on 2025-06-03 04:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_dataset_quality_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='optimizationrun',
            options={'ordering': ['-started_at']},
        ),
        migrations.AddField(
            model_name='optimizationrun',
            name='baseline_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='optimization_runs_baseline', to='core.systemprompt'),
        ),
        migrations.AddField(
            model_name='optimizationrun',
            name='datasets_used',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='optimizationrun',
            name='deployed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='optimizationrun',
            name='evaluation_results',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='optimizationrun',
            name='optimized_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='optimization_runs_optimized', to='core.systemprompt'),
        ),
        migrations.AddField(
            model_name='optimizationrun',
            name='prompt_lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='optimization_runs', to='core.promptlab'),
        ),
        migrations.AddField(
            model_name='optimizationrun',
            name='test_cases_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='optimizationrun',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='optimizationrun',
            name='old_prompt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='optimization_runs_old', to='core.systemprompt'),
        ),
    ]
