# Generated by Django 5.2.1 on 2025-06-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_update_optimization_run_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationrun',
            name='current_step',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='optimizationrun',
            name='progress_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
