# Generated by Django 5.2.1 on 2025-06-04 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_add_optimization_progress_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='optimizationrun',
            name='candidate_metrics',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='optimizationrun',
            name='cost_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='optimizationrun',
            name='detailed_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='optimizationrun',
            name='statistical_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='optimizationrun',
            name='threshold_analysis',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
